### ISSUE TITLE
Building Container locally results in failure

### ISSUE THREAD

**Issue by scetron** [rroemhild/docker-test-openldap#34]
From the latest git repo, I am getting an issue when attempting to build the container locally.

```
 612006e7 @(#) $OpenLDAP: slapd  (Feb 14 2021 18:32:34) $
ldap-test |     Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
ldap-test | 612006e7 hdb_db_open: database "dc=planetexpress,dc=com": database already in use.
ldap-test | 612006e7 backend_startup_one (type=hdb, suffix="dc=planetexpress,dc=com"): bi_db_open failed! (-1)
ldap-test | 612006e7 slapd stopped.
```

I have not changed anything aside from altering the docker-compose.yml

```
version: '2'

services:
    ldap:
        container_name: ldap-test
        # use the image tag to pull directly from the repo
        # image: rroemhild/test-openldap
        environment:
            LDAP_FORCE_STARTTLS: "false"
            LDAP_DOMAIN: "planetexpress.com"
            LDAP_BASEDN: "dc=planetexpress,dc=com"
            LDAP_ORGANISATION: "Planet Express, Inc."
            LDAP_BINDDN: "cn=admin,dc=planetexpress,dc=com"
        # use build tag to use the local repo
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - '10389:10389'
            - '10636:10636'
        volumes:
            - data_volume:/var/lib/ldap/
volumes:
   data_volume:
```

Any insight would be appreciated.
