### ISSUE TITLE
Use with TestContainers, localhost and custom ldif file

### ISSUE THREAD

**Issue by paplorinc** [rroemhild/docker-test-openldap#7]
Hey,

I've tried a few alternative dockerized ldap images, this one is actually working out of the box with an `planetexpress.com` -> `localhost` mapping in `/etc/hosts`.
Is there a better way to be able to use this from TestContainers with `localhost`?
And is there a convenient way to load our own `ldif`, instead of the provided one?

Thanks!

**Comment by rroemhild** [comment]
Hi, not sure about the `/etc/hosts` mapping, in the past I do not need to map the hostname to access the container from localhost or remote hosts.

And to answer your second question, there is no convenient way to load own ldif files. The initial idea for this docker image was to have a fix LDAP setup to run test against it. Maybe that's why it working out of the box :smile:

**Comment by SamyOteroGlez** [comment]
You could donwload/clone the repo and add your own .ldif files under `bootstrap/data/`, then start (rebuild) the container.

I am using docker-compose and following the same ldap structure proposed here. Check below my `docker-compose` file, just place it on the root of the project.

```
version: '2'

services:
    ldap:
        container_name: ldap
        # image: rroemhild/test-openldap
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - '11389:389'
            - '11636:636'
        volumes:
            - data_volume:/var/lib/ldap/
        networks:
            - app_default

volumes:
    data_volume:

networks:
    app_default:
        external:
            name: app_default

```

Cheers
